export const NEW_PAO_LIST = 'NEW_PAO_LIST'
export const ADD_TO_PAO_LIST = 'ADD_TO_PAO_LIST'
export const UPDATE_PAO_LIST = 'UPDATE_PAO_LIST'
export const DELETE_PAO_LIST = 'DELETE_PAO_LIST'
export const FETCHED_PAOLIST = 'FETCHED_PAOLIST'
export const FAILED_TO_FETCH_PAOLIST = 'FAILED_TO_FETCH_PAOLIST'
export const DELETE_PAO_DOC = 'DELETE_PAO_DOC'

export const SIGNED_IN = 'SIGNED_IN'
export const SIGNED_OUT = 'SIGNED_OUT'
export const REFRESHED_TOKENS = 'REFRESHED_TOKENS'
export const SIGNED_UP = 'SIGNED_UP'

//system messages ----
export const SIGN_IN_SUCCESS_MESG = 'SIGN_IN_SUCCESS_MESG'
export const SIGN_IN_FAILED_MESG = 'SIGN_IN_FAILED_MESG'
export const RESET_SIGNIN_MESG = 'RESET_SIGNIN_MESG'

export const SIGN_UP_SUCCESS_MESG = 'SIGN_UP_SUCCESS_MESG'
export const SIGN_UP_FAILED_MESG = 'SIGN_UP_FAILED_MESG'
export const RESET_SIGNUP_MESG = 'RESET_SIGNUP_MESG'

export const RESET_SIGNED_OUT = 'RESET_SIGNED_OUT'
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

export const SAVED_PAOLIST_TO_DB_SUCCESS_MESG = 'SAVED_PAOLIST_TO_DB_SUCCESS_MESG'
export const SAVED_PAOLIST_TO_DB_FAILED_MESG = 'SAVED_PAOLIST_TO_DB_FAILED_MESG'
export const RESET_SAVED_PAOLIST_TO_DB_MESG = 'RESET_SAVED_PAOLIST_TO_DB_MESG'
export const SAVED_PAOLIST_TO_DB_FAILED_NO_TOKEN_MESG = 'SAVED_PAOLIST_TO_DB_FAILED_NO_TOKEN_MESG'

export const UPDATED_DOCUMENT_IN_PAO_SUCCESS_MESG = 'UPDATED_DOCUMENT_IN_PAO_SUCCESS_MESG'
export const UPDATED_DOCUMENT_IN_PAO_FAILED_MESG = 'UPDATED_DOCUMENT_IN_PAO_FAILED_MESG'
export const RESET_UPDATED_DOCUMENT_IN_PAO_MESG = 'RESET_UPDATED_DOCUMENT_IN_PAO_MESG'

export const DELETE_DOCUMENT_IN_PAO_SUCCESS_MESG = 'DELETE_DOCUMENT_IN_PAO_SUCCESS_MESG'
export const DELETE_DOCUMENT_IN_PAO_FAILED_MESG = 'DELETE_DOCUMENT_IN_PAO_FAILED_MESG'
export const RESET_DELETE_DOCUMENT_IN_PAO_MESG = 'RESET_DELETE_DOCUMENT_IN_PAO_MESG'

export const SET_LOADING = 'SET_LOADING'
export const SET_NOT_LOADING = 'SET_NOT_LOADING'

export const INVALID_CREDENTIALS_NOTIFY_MESG = 'INVALID_CREDENTIALS_NOTIFY_MESG'
export const RESET_NOTIFY_MESG = 'RESET_NOTIFY_MESG'
export const INPUT_FIELDS_EMPTY_NOTIFY_MESG = 'INPUT_FIELDS_EMPTY_NOTIFY_MESG'
//system messages ----

