export const NEW_PAO_LIST = 'NEW_PAO_LIST'
export const ADD_TO_PAO_LIST = 'ADD_TO_PAO_LIST'
export const UPDATE_PAO_LIST = 'UPDATE_PAO_LIST'
export const DELETE_PAO_LIST = 'DELETE_PAO_LIST'
export const FETCHED_PAOLIST = 'FETCHED_PAOLIST'
export const FAILED_TO_FETCH_PAOLIST = 'FAILED_TO_FETCH_PAOLIST'
export const DELETE_PAO_DOC = 'DELETE_PAO_DOC'
export const UPDATE_SPECIFIC_PAO_COLLECION = 'UPDATE_SPECIFIC_PAO_COLLECION'
export const CREATED_NEW_PAO_DOC = 'CREATED_NEW_PAO_DOC'

export const SIGNED_IN = 'SIGNED_IN'
export const SIGNED_OUT = 'SIGNED_OUT'
export const REFRESHED_TOKENS = 'REFRESHED_TOKENS'
export const SIGNED_UP = 'SIGNED_UP'

//system messages ----
export const SIGN_IN_SUCCESS_MESG = 'SIGN_IN_SUCCESS_MESG'
export const SIGN_IN_FAILED_MESG = 'SIGN_IN_FAILED_MESG'
export const RESET_SIGNIN_MESG = 'RESET_SIGNIN_MESG'

export const SIGN_UP_SUCCESS_MESG = 'SIGN_UP_SUCCESS_MESG'
export const SIGN_UP_FAILED_MESG = 'SIGN_UP_FAILED_MESG'
export const RESET_SIGNUP_MESG = 'RESET_SIGNUP_MESG'

export const RESET_SIGNED_OUT = 'RESET_SIGNED_OUT'
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

export const SAVED_PAOLIST_TO_DB_SUCCESS_MESG = 'SAVED_PAOLIST_TO_DB_SUCCESS_MESG'
export const SAVED_PAOLIST_TO_DB_FAILED_MESG = 'SAVED_PAOLIST_TO_DB_FAILED_MESG'
export const RESET_SAVED_PAOLIST_TO_DB_MESG = 'RESET_SAVED_PAOLIST_TO_DB_MESG'
export const SAVED_PAOLIST_TO_DB_FAILED_NO_TOKEN_MESG = 'SAVED_PAOLIST_TO_DB_FAILED_NO_TOKEN_MESG'

export const UPDATED_DOCUMENT_IN_PAO_SUCCESS_MESG = 'UPDATED_DOCUMENT_IN_PAO_SUCCESS_MESG'
export const UPDATED_DOCUMENT_IN_PAO_FAILED_MESG = 'UPDATED_DOCUMENT_IN_PAO_FAILED_MESG'
export const RESET_UPDATED_DOCUMENT_IN_PAO_MESG = 'RESET_UPDATED_DOCUMENT_IN_PAO_MESG'

export const DELETE_DOCUMENT_IN_PAO_SUCCESS_MESG = 'DELETE_DOCUMENT_IN_PAO_SUCCESS_MESG'
export const DELETE_DOCUMENT_IN_PAO_FAILED_MESG = 'DELETE_DOCUMENT_IN_PAO_FAILED_MESG'
export const RESET_DELETE_DOCUMENT_IN_PAO_MESG = 'RESET_DELETE_DOCUMENT_IN_PAO_MESG'

export const SET_LOADING = 'SET_LOADING'
export const SET_NOT_LOADING = 'SET_NOT_LOADING'

export const INVALID_CREDENTIALS_NOTIFY_MESG = 'INVALID_CREDENTIALS_NOTIFY_MESG'
export const RESET_NOTIFY_MESG = 'RESET_NOTIFY_MESG'
export const INPUT_FIELDS_EMPTY_NOTIFY_MESG = 'INPUT_FIELDS_EMPTY_NOTIFY_MESG'

//system messages ----

export const TOGGLE_FAB_VISIBILITY = 'TOGGLE_FAB_VISIBILITY'
export const TOGGLE_FAB_VISIBILITY_TRUE = 'TOGGLE_FAB_VISIBILITY_TRUE'
export const TOGGLE_FAB_VISIBILITY_FALSE = 'TOGGLE_FAB_VISIBILITY_FALSE'
export const SAVE_CURRENT_SCREEN = 'SAVE_CURRENT_SCREEN'
export const TOGGLE_CONFIGURATION_EDIT_MODE = 'TOGGLE_CONFIGURATION_EDIT_MODE'
export const TOGGLE_CONFIGURATION_PAGINATION = 'TOGGLE_CONFIGURATION_PAGINATION'
export const UPDATE_FAB_ACTION_PROPERTIES = 'UPDATE_FAB_ACTION_PROPERTIES'
export const UPDATE_MAIN_FAB_PROPERTIES = 'UPDATE_MAIN_FAB_PROPERTIES'
export const UPDATE_MANY_SCREEN_CONFIGURATIONS_AT_ONCE = 'UPDATE_MANY_SCREEN_CONFIGURATIONS_AT_ONCE'

export const DELETE_ID_FAV_LIST = 'DELETE_ID_FAV_LIST'
export const ADD_TO_FAV_LIST = 'ADD_TO_FAV_LIST'

export const UPDATE_FLASHCARD_ITEM_DISPLAY_ON_WHAT_SIDE = 'UPDATE_FLASHCARD_ITEM_DISPLAY_ON_WHAT_SIDE'
export const SET_AUTO_PLAY_DURATION = 'SET_AUTO_PLAY_DURATION'
export const TOGGLE_AUTO_PLAY_DURATION = 'TOGGLE_AUTO_PLAY_DURATION'
export const SAVED_FLASHCARD_SETTINGS_FROM_MODAL = 'SAVED_FLASHCARD_SETTINGS_FROM_MODAL'
export const UPDATE_FLASHCARD_ORDER = 'UPDATE_FLASHCARD_ORDER'

export const PAOTABLE_SCREEN_SETTINGS = 'PAOTABLE_SCREEN_SETTINGS'
export const FLASHCARDS_SCREEN_SETTINGS = 'FLASHCARDS_SCREEN_SETTINGS'
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE'

export const FAILED_SERVER_CRUD_REQUEST = 'FAILED_SERVER_CRUD_REQUEST'

export const SAVE_CONTROLLED_THEME_COLOR = 'SAVE_CONTROLLED_THEME_COLOR'
export const RESET_CONTROLLED_THEME_COLOR = 'RESET_CONTROLLED_THEME_COLOR'

export const CURRENT_STUDY_CARD = 'CURRENT_STUDY_CARD'
export const STUDY_MODE_TOGGLE = 'STUDY_MODE_TOGGLE'
export const GENERATED_STUDY_SETS = 'GENERATED_STUDY_SETS'
export const DELETE_STUDY_SETS = 'DELETE_STUDY_SETS'

export const STUDY_MODE_TOGGLE_OFF = 'STUDY_MODE_TOGGLE_OFF'